// Maps the "nationality" values found in our database to flagcdn.com codes.
// flagcdn.com is a free flag-image CDN, no API key needed:
// https://flagcdn.com/{size}/{code}.png
//
// A few entries use flagcdn's non-ISO extension codes for UK home nations
// (gb-eng, gb-sct, gb-wls), since England/Scotland/Wales compete as separate
// national teams in football despite not being ISO 3166-1 countries.
//
// If a new nationality shows up in a future database update that isn't in
// this list, the flag is simply omitted (no broken image) — add it here
// when you spot it missing.

export const NATIONALITY_TO_CODE = {
  "Albania": "al",
  "Algeria": "dz",
  "Angola": "ao",
  "Argentina": "ar",
  "Armenia": "am",
  "Australia": "au",
  "Austria": "at",
  "Azerbaijan": "az",
  "Bahrain": "bh",
  "Belarus": "by",
  "Belgium": "be",
  "Benin": "bj",
  "Bolivia": "bo",
  "Bosnia and Herzegovina": "ba",
  "Botswana": "bw",
  "Brazil": "br",
  "Bulgaria": "bg",
  "Burkina Faso": "bf",
  "Burundi": "bi",
  "Cameroon": "cm",
  "Canada": "ca",
  "Cape Verde": "cv",
  "Central African Republic": "cf",
  "Chile": "cl",
  "Colombia": "co",
  "Comoros": "km",
  "Congo": "cg",
  "Congo DR": "cd",
  "Costa Rica": "cr",
  "Croatia": "hr",
  "Cyprus": "cy",
  "Czech Republic": "cz",
  "Czechia": "cz",
  "DR Congo": "cd",
  "Denmark": "dk",
  "Ecuador": "ec",
  "Egypt": "eg",
  "El Salvador": "sv",
  "England": "gb-eng",
  "Equatorial Guinea": "gq",
  "Estonia": "ee",
  "FYR Macedonia": "mk",
  "Faroe Islands": "fo",
  "Finland": "fi",
  "France": "fr",
  "Gabon": "ga",
  "Gambia": "gm",
  "Georgia": "ge",
  "Germany": "de",
  "Ghana": "gh",
  "Gibraltar": "gi",
  "Greece": "gr",
  "Greenland": "gl",
  "Guinea": "gn",
  "Guinea-Bissau": "gw",
  "Haiti": "ht",
  "Honduras": "hn",
  "Hungary": "hu",
  "Iceland": "is",
  "Iran": "ir",
  "Iraq": "iq",
  "Israel": "il",
  "Italy": "it",
  "Ivory Coast": "ci",
  "Jamaica": "jm",
  "Japan": "jp",
  "Jordan": "jo",
  "Kenya": "ke",
  "Kosovo": "xk",
  "Kyrgyzstan": "kg",
  "Latvia": "lv",
  "Liberia": "lr",
  "Liechtenstein": "li",
  "Lithuania": "lt",
  "Luxembourg": "lu",
  "Macedonia": "mk",
  "Malawi": "mw",
  "Mali": "ml",
  "Martinique": "mq",
  "Mauritania": "mr",
  "Mexico": "mx",
  "Moldova": "md",
  "Mongolia": "mn",
  "Montenegro": "me",
  "Morocco": "ma",
  "Netherlands": "nl",
  "New Zealand": "nz",
  "Nicaragua": "ni",
  "Niger": "ne",
  "Nigeria": "ng",
  "Norway": "no",
  "Panama": "pa",
  "Peru": "pe",
  "Philippines": "ph",
  "Poland": "pl",
  "Portugal": "pt",
  "Republic of Ireland": "ie",
  "Romania": "ro",
  "Russia": "ru",
  "Rwanda": "rw",
  "Scotland": "gb-sct",
  "Senegal": "sn",
  "Serbia": "rs",
  "Sierra Leone": "sl",
  "Slovakia": "sk",
  "Slovenia": "si",
  "South Africa": "za",
  "South Korea": "kr",
  "Spain": "es",
  "Suriname": "sr",
  "Sweden": "se",
  "Switzerland": "ch",
  "Syria": "sy",
  "São Tomé e Príncipe": "st",
  "Taiwan": "tw",
  "Tajikistan": "tj",
  "Tanzania": "tz",
  "Togo": "tg",
  "Trinidad and Tobago": "tt",
  "Tunisia": "tn",
  "Turkey": "tr",
  "USA": "us",
  "Uganda": "ug",
  "Ukraine": "ua",
  "Uruguay": "uy",
  "Uzbekistan": "uz",
  "Venezuela": "ve",
  "Wales": "gb-wls",
  "Zambia": "zm",
  "Zimbabwe": "zw",
};

export function flagUrl(nationality, size = "24x18") {
  if (!nationality) return null;
  const code = NATIONALITY_TO_CODE[nationality];
  if (!code) return null;
  return `https://flagcdn.com/${size}/${code}.png`;
}
